### ISSUE TITLE
NullReferenceException in DotNetInstanceCallbackHandler.ClearTimeoutTimer()

### ISSUE THREAD

**Issue by MikaBerglund** [Blazorade/Blazorade-Core#12]
In certain situations, the DotNetInstanceCallbackHandler.ClearTimeoutTimer() method will cause a null reference exception. The full stack trace is

```
blazor.server.js:1 Uncaught (in promise) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorade.Core.Interop.DotNetInstanceCallbackHandler`2.ClearTimeoutTimer()
   at Blazorade.Core.Interop.DotNetInstanceCallbackHandler`2.SuccessCallbackAsync(TSuccess result)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (https://localhost:5001/_framework/blazor.server.js:1:70292)
    at e.<anonymous> (https://localhost:5001/_framework/blazor.server.js:8:119012)
    at https://localhost:5001/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:26263)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:24201)
    at e.connection.onreceive (https://localhost:5001/_framework/blazor.server.js:1:17286)
    at WebSocket.i.onmessage (https://localhost:5001/_framework/blazor.server.js:1:46503)
```

**Comment by MikaBerglund** [comment]
This seems to be caused by JavaScript calling the callback before the timeout timer has been created, thus resulting in a null reference exception.
